[package]
name = "dvsynth"
version = "0.1.0"
authors = ["Jakub Hlusička <jakub.hlusicka@email.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["iced/debug"]

[dependencies]
iced = { path = "../iced" }
iced_native = { path = "../iced/native" }
iced_graphics = { path = "../iced/graphics" }
iced_wgpu = { path = "../iced/wgpu" }
