[package]
name = "dvsynth"
version = "0.1.0"
authors = ["Jakub Hlusička <jakub.hlusicka@email.cz>"]
license = "AGPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["iced/debug"]

[dependencies]
iced = { version = "0.13", features = ["canvas"] }
iced_graphics = "0.13"
iced_runtime = "0.13"
iced_wgpu = "0.13"
iced_winit = "0.13"
iced_futures = "0.13"
iced_core = "0.13"
# iced = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler", features = ["canvas"] }
# iced_graphics = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler", features = ["canvas"] }
# iced_native = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler" }
# iced_wgpu = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler", features = ["canvas"] }
# iced_winit = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler" }
# iced_futures = { git = "https://github.com/Limeth/iced.git", branch = "feature-event-handler" }
arc-swap = "1.7.1"
byteorder = "1"
downcast-rs = "1.2.0"
dyn-clone = "1.0.3"
flume = { version = "0.11.0", default-features = false }
indexmap = "2.2.6"
lyon_geom = "1.0.5"
ordered-float = "4.2.0"
paste = "1.0"
petgraph = "0.6.4"
roots = "*"
smallvec = "1.4"
static_assertions = "1.1.0"
vek = "0.17.2"
sharded-slab = "0.1.0"
lazy_static = "1.4.0"
crossbeam = "0.8.0"
safe-transmute = "0.11.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "doc/katex.html" ]
