name: Test
on: [push, pull_request]
jobs:
  native:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: hecrj/setup-rust-action@v1.3
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@2
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features
