name: Format
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt
        rust-version: nightly
    - uses: actions/checkout@master
    - name: Check format
      run: cargo fmt --all -- --check
